name: UPWC
favicon: null
layout_spectrum: 0.36624
typography_spectrum: 0.7179760292638093
title: UltraPedestrian Wilderness Challenge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5
  lightness: 0.9195242077112198
  saturation: 0.9375
  rhythmicContrast: 0.958621226483956
purpose: []
